<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb7f9a9f2712adb840b1a6876c8dca806
{
    public static $prefixLengthsPsr4 = array (
        'n' => 
        array (
            'notification\\' => 13,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'notification\\' => 
        array (
            0 => __DIR__ . '/../..' . '/_app',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb7f9a9f2712adb840b1a6876c8dca806::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb7f9a9f2712adb840b1a6876c8dca806::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb7f9a9f2712adb840b1a6876c8dca806::$classMap;

        }, null, ClassLoader::class);
    }
}
